Repository jacildoaldrin/tpc_inventory_frontend, pull requests merged in 2020-10, with the labels that each got.

#12 TIW72: Table overflowx to be scrollable instead
  src/components/Details/StorageDetails/StorageDetails.js
  src/components/Tables/ProductsTable/ProductsTable.js
  src/components/Tables/StorageTable/StorageTable.js
  src/components/Tables/SuppliersTable/SuppliersTable.js
Labels: enhancement

#21 TIW86: Replaced searchbar with a dropdown menu
  src/components/Tables/StorageTable/StorageTable.js
Labels: replaced

#25 Add back button chevron on all (1) PULL page(s)
  src/components/ProductActions/Pull.js
Labels: UX/UI Fix

#20 Added product code and supplier code search functionality
  src/components/Tables/ProductsTable/ProductsTable.js
  src/components/Tables/SuppliersTable/SuppliersTable.js
Labels: enhancement

#37 Snackbar message and supplier table refresh done
  src/components/Forms/AddSupplier/AddSupplier.js
  src/components/Tables/SuppliersTable/SuppliersTable.js
  src/contexts/SuppliersContext.js
Labels: bug, enhancement

#36 snackbar optional changes
  src/components/Forms/AddSupplier/AddSupplier.js
  src/components/ProductActions/Pull.js
  src/components/ProductActions/Push.js
  src/containers/Products/Products.js
  src/contexts/ProductsContext.js
  src/contexts/SnackbarContext.js
  src/contexts/StorageContext.js
  src/contexts/SuppliersContext.js
Labels: UX/UI Fix

#43 push quantity validation fix
  src/components/ProductActions/Push.js
Labels: bug
